import { conflict } from './errors.js';

const maps = Object.freeze({
  order: {
    PENDING_PAYMENT: ['PAYMENT_PROCESSING', 'CANCELLED'],
    PAYMENT_PROCESSING: ['PAID', 'PENDING_PAYMENT', 'CANCELLED', 'DISPUTED'],
    PAID: ['PROCESSING', 'CANCELLED', 'DISPUTED', 'REFUND_PENDING'],
    PROCESSING: ['READY', 'CANCELLED', 'DISPUTED', 'REFUND_PENDING'],
    READY: ['IN_TRANSIT', 'CANCELLED', 'DISPUTED'],
    IN_TRANSIT: ['OUT_FOR_DELIVERY', 'DELIVERED', 'DISPUTED'],
    OUT_FOR_DELIVERY: ['DELIVERED', 'DISPUTED'],
    DELIVERED: ['DISPUTED', 'REFUND_PENDING'],
    DISPUTED: ['REFUND_PENDING', 'PROCESSING', 'CANCELLED'],
    REFUND_PENDING: ['REFUNDED', 'DISPUTED'],
    REFUNDED: [], CANCELLED: [],
  },
  sourcing: {
    DRAFT: ['REQUEST_SUBMITTED', 'CANCELLED'],
    REQUEST_SUBMITTED: ['UNDER_REVIEW', 'MORE_INFO_REQUIRED', 'CANCELLED'],
    UNDER_REVIEW: ['MORE_INFO_REQUIRED', 'QUOTE_READY', 'CANCELLED'],
    MORE_INFO_REQUIRED: ['REQUEST_SUBMITTED', 'CANCELLED'],
    QUOTE_READY: ['AWAITING_PAYMENT', 'UNDER_REVIEW', 'CANCELLED'],
    AWAITING_PAYMENT: ['PAYMENT_CONFIRMED', 'CANCELLED'],
    PAYMENT_CONFIRMED: ['PROCUREMENT_IN_PROGRESS', 'CANCELLED'],
    PROCUREMENT_IN_PROGRESS: ['PROCURED', 'CANCELLED'],
    PROCURED: ['INTERNATIONAL_TRANSIT'],
    INTERNATIONAL_TRANSIT: ['ARRIVED_IN_COUNTRY'],
    ARRIVED_IN_COUNTRY: ['LOCAL_FULFILMENT'],
    LOCAL_FULFILMENT: ['COMPLETED'],
    COMPLETED: [], CANCELLED: [],
  },
  kyc: { DRAFT: ['SUBMITTED'], SUBMITTED: ['UNDER_REVIEW'], UNDER_REVIEW: ['APPROVED', 'REJECTED'], APPROVED: [], REJECTED: ['SUBMITTED'] },
  dispute: {
    OPEN: ['UNDER_REVIEW', 'AWAITING_BUYER', 'AWAITING_SELLER', 'CLOSED'],
    UNDER_REVIEW: ['AWAITING_BUYER', 'AWAITING_SELLER', 'RESOLVED_BUYER', 'RESOLVED_SELLER', 'CLOSED'],
    AWAITING_BUYER: ['UNDER_REVIEW', 'RESOLVED_BUYER', 'RESOLVED_SELLER', 'CLOSED'],
    AWAITING_SELLER: ['UNDER_REVIEW', 'RESOLVED_BUYER', 'RESOLVED_SELLER', 'CLOSED'],
    RESOLVED_BUYER: ['CLOSED'], RESOLVED_SELLER: ['CLOSED'], CLOSED: [],
  },
  payout: {
    REQUESTED: ['UNDER_REVIEW', 'CANCELLED'], UNDER_REVIEW: ['APPROVED', 'REJECTED'],
    APPROVED: ['PROCESSING', 'CANCELLED'], PROCESSING: ['PAID', 'REJECTED'],
    PAID: [], REJECTED: [], CANCELLED: [],
  },
  booking: {
    REQUESTED: ['ACCEPTED', 'CANCELLED'], ACCEPTED: ['IN_PROGRESS', 'CANCELLED'],
    IN_PROGRESS: ['COMPLETED', 'DISPUTED'], COMPLETED: ['DISPUTED'], DISPUTED: [], CANCELLED: [],
  },
  delivery: {
    ASSIGNED: ['PICKED_UP', 'CANCELLED'], PICKED_UP: ['IN_TRANSIT', 'FAILED'],
    IN_TRANSIT: ['OUT_FOR_DELIVERY', 'DELIVERED', 'FAILED'], OUT_FOR_DELIVERY: ['DELIVERED', 'FAILED'],
    DELIVERED: [], FAILED: ['ASSIGNED', 'CANCELLED'], CANCELLED: [],
  },
});

export function assertTransition(domain, from, to) {
  if (from === to) return;
  if (!maps[domain]?.[from]?.includes(to)) {
    throw conflict('INVALID_STATE_TRANSITION', `${domain} cannot move from ${from} to ${to}.`);
  }
}

export function allowedTransitions(domain, from) {
  return maps[domain]?.[from] || [];
}
