import{useEffect,useState}from'react';
import{useParams,Link,useNavigate}from'react-router-dom';
import{Heart,GitCompareArrows,MessageCircle}from'lucide-react';
import{api}from'../../api/client.js';
import{useCart}from'../../state/CartContext.jsx';
import{useAuth}from'../../auth/AuthContext.jsx';
export function ProductPage(){
 const{id}=useParams(),[p,setP]=useState(null),[reviews,setReviews]=useState([]),[saved,setSaved]=useState(''),[reviewError,setReviewError]=useState(''),cart=useCart(),{user}=useAuth(),nav=useNavigate();
 const loadReviews=()=>api(`/reviews/product/${id}`).then(setReviews);useEffect(()=>{Promise.all([api(`/products/${id}`),loadReviews()]).then(([a])=>setP(a))},[id]);
 const guarded=fn=>async()=>{if(!user){nav('/auth');return}try{await fn()}catch(e){setSaved(e.message)}};
 const collect=type=>guarded(async()=>{await api(`/collections/${type}/${id}`,{method:'POST'});setSaved(type==='wishlist'?'Saved to wishlist.':'Added to compare.')});
 const messageSeller=guarded(async()=>{const c=await api('/messages/conversations',{method:'POST',body:JSON.stringify({user_id:p.seller_id})});nav(`/messages/${c.id}`)});
 async function submitReview(e){e.preventDefault();if(!user){nav('/auth');return}const fd=new FormData(e.currentTarget);try{await api('/reviews',{method:'POST',body:JSON.stringify({product_id:id,rating:Number(fd.get('rating')),comment:fd.get('comment')})});e.currentTarget.reset();loadReviews()}catch(e){setReviewError(e.message)}}
 async function deleteReview(reviewId){try{await api(`/reviews/${reviewId}`,{method:'DELETE'});loadReviews()}catch(e){setReviewError(e.message)}}
 if(!p)return <div className="page-wrap">Loading product…</div>;
 return <div className="page-wrap product-detail"><div className="product-gallery">{p.image_url?<img src={p.image_url} alt={p.name}/>:<div className="placeholder big">BUYSELL</div>}</div><div><span className="eyebrow">{p.category||'Marketplace'}</span><h1>{p.name}</h1><p>{p.description}</p><div className="price">₦{(Number(p.flash_price||p.price)/100).toLocaleString()}</div><p className="muted">Sold by <Link to={`/store/${p.seller_id}`}>{p.store_name||p.seller_name||'Seller'}</Link> · {p.review_count||0} reviews</p><div className="action-row"><button className="button" onClick={()=>cart.add(p)}>Add to cart</button><button className="button secondary" onClick={collect('wishlist')}><Heart size={17}/> Wishlist</button><button className="button secondary" onClick={collect('compare')}><GitCompareArrows size={17}/> Compare</button><button className="button secondary" onClick={messageSeller}><MessageCircle size={17}/> Message</button></div>{saved&&<p className="success">{saved}</p>}</div><section className="full-span"><h2>Buyer reviews</h2>{user&&<form className="stack form-card" onSubmit={submitReview}><select name="rating" defaultValue="5"><option value="5">5 stars</option><option value="4">4 stars</option><option value="3">3 stars</option><option value="2">2 stars</option><option value="1">1 star</option></select><textarea name="comment" placeholder="Write a review"/><button className="button secondary">Save review</button></form>}{reviewError&&<p className="error">{reviewError}</p>}<div className="list section-gap">{reviews.length?reviews.map(r=><div className="review" key={r.id}><div className="page-title-row"><strong>{r.reviewer_name||'Buyer'} · {r.rating}/5</strong>{user?.id===r.reviewer_id&&<button className="text-btn danger-text" onClick={()=>deleteReview(r.id)}>Delete</button>}</div><p>{r.comment||r.review_text}</p>{r.verified_purchase&&<small className="muted">Verified purchase</small>}</div>):<p>No reviews yet.</p>}</div></section></div>
}
