import { Link,useLocation } from 'react-router-dom';

const upcoming=['Native Android app download from the brand landing page','Role-specific buyer, seller, supplier, manager and rider experiences','Play Store and App Store publishing — coming soon','Expanded supplier integrations and automated fulfillment'];

export function StaticPage(){
 const key=useLocation().pathname.slice(1);
 if(key==='terms') return <Legal title="Terms of Service & Marketplace Agreement" updated="April 2026"><h2>1. General Terms</h2><p>By creating an account on BUYSELL Nigeria, you agree to these Terms of Service. BUYSELL operates as a marketplace platform connecting buyers, sellers, suppliers and delivery participants. BUYSELL provides the platform infrastructure and does not directly own third-party marketplace inventory.</p><h2>2. Seller Obligations</h2><ul><li>All listed products must be genuine and accurately described.</li><li>Sellers must respond to orders promptly and keep fulfillment information current.</li><li>Basic seller dashboard access may be supplemented by optional paid promotions or premium services.</li><li>Fraudulent or misleading listings may result in account suspension or termination.</li></ul><h2>3. Buyer Protection</h2><ul><li>Online payments are processed through the payment provider shown at checkout and verified server-side by BUYSELL.</li><li>If a product does not match its description, buyers can open a dispute from the order/dispute pages.</li><li>For bank-transfer orders, buyers may be required to provide payment proof.</li><li>Reviews must reflect genuine purchasing experiences.</li></ul><h2>4. Marketplace Participants</h2><p>Suppliers, seller managers and riders act within permissions assigned to their accounts. They are responsible for accurate information, professional conduct and compliance with applicable law.</p><h2>5. Prohibited Activities</h2><ul><li>Selling counterfeit, stolen or illegal goods.</li><li>Manipulating reviews or ratings.</li><li>Harassing other users.</li><li>Using the platform for fraud, money laundering or unlawful transactions.</li><li>Attempting to bypass transaction safety checks, role permissions or platform rules.</li></ul><h2>6. Dispute Resolution</h2><p>Disputes are reviewed using order history and evidence submitted by the parties. Matters may be escalated to the appropriate Nigerian consumer-protection or legal authority where required.</p><h2>7. Account Termination</h2><p>BUYSELL may suspend or terminate accounts that violate these terms or create security, fraud or legal risk.</p><h2>8. Questions</h2><p>For questions about these terms, contact support@buysell.ng.</p></Legal>;
 if(key==='privacy') return <Legal title="Privacy Policy" updated="April 2026"><h2>Data We Collect</h2><p>We collect account details, profile and store information, delivery details, messages, transaction history, KYC submissions and security metadata needed to provide the marketplace.</p><h2>How We Protect Your Data</h2><p>Traffic is protected in transit with TLS. Sensitive operations are performed by the BUYSELL backend rather than directly from the browser to the database. Passwords are stored as one-way password hashes, and secrets remain server-side.</p><h2>Information Sharing</h2><p>Information is shared only as needed for marketplace fulfillment, payments, delivery, fraud prevention and legal compliance. BUYSELL does not sell personal information to advertisers.</p><h2>Your Rights</h2><p>You may update your profile, manage delivery addresses and request account deletion from your account pages. Certain transaction, dispute, fraud-prevention, tax and accounting records may be retained when legally or operationally required.</p><h2>Account Deletion</h2><p>Signed-in users can open the Account page and request deletion. Login access is disabled and personal profile data is removed or minimized where possible while required marketplace records are retained.</p></Legal>;
 return <div className="page-wrap narrow"><span className="eyebrow">Roadmap</span><h1>Upcoming</h1><p>BUYSELL V1.2 separates the marketplace application from the public brand/download site so product work can grow independently.</p><div className="list section-gap">{upcoming.map(x=><div className="list-row" key={x}><strong>{x}</strong></div>)}</div></div>;
}
function Legal({title,updated,children}){return <div className="page-wrap narrow legal-document"><span className="eyebrow">BUYSELL Nigeria</span><h1>{title}</h1><p className="muted">Last updated: {updated}</p>{children}<div className="action-row section-gap"><Link className="button" to="/shop">Back to BUYSELL</Link><Link className="button secondary" to={title.startsWith('Terms')?'/privacy':'/terms'}>{title.startsWith('Terms')?'Privacy Policy':'Terms of Service'}</Link></div></div>}
