import {
  ArrowRight, BadgeCheck, BarChart3, Boxes, Check, ChevronRight, CircleDollarSign,
  Download, FileText, Filter, MoreHorizontal, Package, Plus, Search, Settings,
  ShieldCheck, ShoppingBag, Store, TrendingDown, TrendingUp, Truck, Upload,
  UserPlus, UsersRound, WalletCards,
} from 'lucide-react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useMemo, useState, type FormEvent, type ReactNode } from 'react';
import { Link, useLocation, useNavigate, useParams } from 'react-router-dom';
import { EmptyState, ErrorState, PageLoader } from '../components/States';
import { Seo } from '../components/Seo';
import { useToast } from '../contexts/ToastContext';
import { api } from '../lib/api';
import { formatDate, formatMoney, titleFromSlug } from '../lib/format';
import type { ActivityRow, DashboardData, Metric, PageResult, Product } from '../lib/types';

type WorkspaceKind = 'seller' | 'supplier' | 'admin';

const kindLabel = { seller: 'Seller centre', supplier: 'Supplier portal', admin: 'Control room' };

export function DashboardPage({ kind }: { kind: WorkspaceKind }) {
  const endpoint = kind === 'admin' ? '/admin/dashboard' : `/${kind}/dashboard`;
  const dashboard = useQuery({ queryKey: [kind, 'dashboard'], queryFn: () => api.get<DashboardData>(endpoint), staleTime: 30_000 });
  const title = kind === 'admin' ? 'Platform overview' : kind === 'supplier' ? 'Supply overview' : 'Store overview';

  return (
    <><Seo title={`${title} · ${kindLabel[kind]}`} noIndex /><div className="workspace-page"><header className="workspace-page__heading"><div><span className="eyebrow">{kindLabel[kind]}</span><h2>{title}</h2><p>{kind === 'admin' ? 'Monitor marketplace health, risk and operations.' : 'A focused view of today’s activity and what needs attention.'}</p></div><div>{kind === 'seller' && <Link className="button button--primary" to="/seller/products/new"><Plus /> Add product</Link>}{kind === 'supplier' && <Link className="button button--primary" to="/supplier/requests">View requests <ArrowRight /></Link>}{kind === 'admin' && <button className="button button--secondary"><Download /> Export report</button>}</div></header>{dashboard.isLoading ? <PageLoader label="Preparing dashboard" /> : dashboard.isError ? <ErrorState title="Dashboard unavailable" message={dashboard.error.message} onRetry={() => void dashboard.refetch()} /> : dashboard.data && <><MetricGrid metrics={dashboard.data.metrics} />{dashboard.data.chart?.length ? <div className="dashboard-grid"><ChartCard values={dashboard.data.chart} title={kind === 'admin' ? 'Marketplace volume' : 'Sales performance'} /><article className="surface-card action-card"><h3>Operational focus</h3><p>Use the navigation to review records that need attention. Every available action is permission checked by the BUYSELL API.</p><Link className="button button--secondary button--full" to={kind === 'admin' ? '/admin/orders' : kind === 'supplier' ? '/supplier/requests' : '/seller/orders'}>Open work queue <ArrowRight /></Link></article></div> : null}<RecentActivity rows={dashboard.data.rows} title={kind === 'admin' ? 'Latest platform activity' : 'Recent orders'} /></>}</div></>
  );
}

function MetricGrid({ metrics }: { metrics: Metric[] }) {
  const icons = [CircleDollarSign, ShoppingBag, BarChart3, WalletCards];
  return <section className="metric-grid" aria-label="Key metrics">{metrics.map((metric, index) => { const MetricIcon = icons[index % icons.length]!; return <article key={metric.label}><div><span><MetricIcon /></span><small>{metric.label}</small></div><strong>{metric.value}</strong>{metric.change && <p className={`metric-change metric-change--${metric.trend}`}>{metric.trend === 'up' ? <TrendingUp /> : metric.trend === 'down' ? <TrendingDown /> : null}{metric.change}</p>}</article>; })}</section>;
}

function ChartCard({ values, title }: { values: number[]; title: string }) {
  const max = Math.max(...values, 1);
  return <article className="surface-card chart-card"><div><div><small>Last 12 weeks</small><h3>{title}</h3></div><select aria-label="Chart period"><option>12 weeks</option><option>30 days</option></select></div><div className="bar-chart" aria-label={`${title} bar chart`}>{values.map((value, index) => <span key={index} style={{ height: `${Math.max(8, value / max * 100)}%` }} title={`${value}`} />)}</div><div className="chart-labels"><span>May</span><span>June</span><span>July</span><span>August</span></div></article>;
}

function RecentActivity({ rows, title }: { rows: ActivityRow[]; title: string }) {
  return <section className="surface-card data-section"><div className="data-section__head"><div><h3>{title}</h3><p>Live operational records from BUYSELL.</p></div><button className="button button--text">View all <ArrowRight /></button></div><div className="data-table"><table><thead><tr><th>Reference</th><th>Status</th><th>Value</th><th>Updated</th><th><span className="sr-only">Actions</span></th></tr></thead><tbody>{rows.map((row) => <tr key={row.id}><td><strong>{row.primary}</strong><small>{row.secondary}</small></td><td><span className={`status status--${row.status.toLowerCase().replaceAll(' ', '-')}`}>{row.status}</span></td><td><strong>{row.value ?? '—'}</strong></td><td>{row.date ?? '—'}</td><td><button className="icon-button icon-button--small" aria-label={`Actions for ${row.primary}`}><MoreHorizontal /></button></td></tr>)}</tbody></table></div></section>;
}

interface WorkspaceConfig {
  title: string;
  intro: string;
  singular: string;
  endpoint: string;
  createPath?: string;
  columns: string[];
  empty: string;
}

const pageConfig: Record<string, WorkspaceConfig> = {
  products: { title: 'Products', intro: 'Create clear listings and keep every offer accurate.', singular: 'product', endpoint: '/seller/products', createPath: '/seller/products/new', columns: ['Product', 'Stock', 'Status', 'Price'], empty: 'Publish your first product to start building your storefront.' },
  inventory: { title: 'Inventory', intro: 'Track available, reserved and low-stock units.', singular: 'inventory item', endpoint: '/seller/inventory', columns: ['Product', 'Available', 'Reserved', 'Status'], empty: 'Inventory appears after a product has a sellable variant.' },
  orders: { title: 'Orders', intro: 'Process paid orders and keep fulfilment moving.', singular: 'order', endpoint: '/seller/orders', columns: ['Order', 'Customer', 'Status', 'Total'], empty: 'Paid customer orders will appear here.' },
  customers: { title: 'Customers', intro: 'Understand customers through completed marketplace activity.', singular: 'customer', endpoint: '/seller/customers', columns: ['Customer', 'Orders', 'Last order', 'Value'], empty: 'Customer records appear after eligible orders.' },
  messages: { title: 'Messages', intro: 'Keep buyer conversations organised and on-platform.', singular: 'conversation', endpoint: '/seller/messages', columns: ['Conversation', 'Order', 'Status', 'Updated'], empty: 'New buyer conversations will appear here.' },
  analytics: { title: 'Analytics', intro: 'Understand product, order and store performance.', singular: 'report', endpoint: '/seller/analytics', columns: ['Metric', 'Current', 'Previous', 'Change'], empty: 'Analytics populate as your store receives traffic and orders.' },
  finance: { title: 'Finance', intro: 'Review sales, commissions, adjustments and available funds.', singular: 'transaction', endpoint: '/seller/finance', columns: ['Transaction', 'Type', 'Status', 'Amount'], empty: 'Financial transactions will appear after payment activity.' },
  payouts: { title: 'Payouts', intro: 'Request eligible funds and track payout status.', singular: 'payout', endpoint: '/seller/payouts', columns: ['Payout', 'Destination', 'Status', 'Amount'], empty: 'Payout requests will appear here.' },
  advertising: { title: 'Advertising', intro: 'Promote eligible products with controlled campaigns.', singular: 'campaign', endpoint: '/seller/advertising', createPath: '/seller/advertising/new', columns: ['Campaign', 'Period', 'Status', 'Spend'], empty: 'Create a campaign when you are ready to grow product visibility.' },
  referrals: { title: 'Referrals', intro: 'Track eligible referrals and rewards.', singular: 'referral', endpoint: '/seller/referrals', columns: ['Referral', 'Joined', 'Status', 'Reward'], empty: 'Your referred businesses will appear here.' },
  team: { title: 'Team', intro: 'Give teammates only the permissions they need.', singular: 'team member', endpoint: '/seller/team', columns: ['Member', 'Role', 'Status', 'Last active'], empty: 'Invite a teammate to collaborate on this store.' },
  verification: { title: 'Verification', intro: 'Keep business verification information current.', singular: 'submission', endpoint: '/seller/verification', columns: ['Check', 'Submitted', 'Status', 'Updated'], empty: 'Required verification steps will appear here.' },
  sourcing: { title: 'Product sourcing', intro: 'Request products, review quotes and track fulfilment.', singular: 'sourcing request', endpoint: '/sourcing/requests', createPath: '/seller/sourcing/new', columns: ['Request', 'Quantity', 'Status', 'Quote'], empty: 'Start a sourcing request for a product your business needs.' },
  settings: { title: 'Store settings', intro: 'Manage storefront, fulfilment and notification preferences.', singular: 'setting', endpoint: '/seller/settings', columns: ['Setting', 'Value', 'Status', 'Updated'], empty: 'Store preferences will appear here.' },
  'supplier-profile': { title: 'Supplier profile', intro: 'Present an accurate, verifiable supply capability.', singular: 'profile item', endpoint: '/supplier/profile', columns: ['Field', 'Value', 'Status', 'Updated'], empty: 'Complete your supplier profile to receive qualified requests.' },
  catalog: { title: 'Supply catalog', intro: 'Describe the products and capacity your business can supply.', singular: 'catalog item', endpoint: '/supplier/catalog', columns: ['Item', 'Minimum quantity', 'Status', 'Lead time'], empty: 'Add a catalog item to show buyers what you can supply.' },
  requests: { title: 'Open requests', intro: 'Review eligible business demand and prepare clear quotes.', singular: 'request', endpoint: '/supplier/requests', columns: ['Request', 'Quantity', 'Status', 'Deadline'], empty: 'Matching quotation requests will appear here.' },
  'supplier-orders': { title: 'Supply orders', intro: 'Track approved supplier commitments and fulfilment.', singular: 'supply order', endpoint: '/supplier/orders', columns: ['Order', 'Buyer', 'Status', 'Value'], empty: 'Approved supply orders will appear here.' },
  'supplier-verification': { title: 'Supplier verification', intro: 'Complete the checks needed for qualified supply opportunities.', singular: 'submission', endpoint: '/supplier/verification', columns: ['Check', 'Submitted', 'Status', 'Updated'], empty: 'Verification requirements will appear here.' },
};

export function WorkspaceListPage({ kind, section }: { kind: 'seller' | 'supplier'; section: string }) {
  const configKey = kind === 'supplier' && section === 'profile' ? 'supplier-profile' : kind === 'supplier' && section === 'orders' ? 'supplier-orders' : kind === 'supplier' && section === 'verification' ? 'supplier-verification' : section;
  const config = pageConfig[configKey] ?? { title: titleFromSlug(section), intro: `Manage ${titleFromSlug(section).toLowerCase()} for your ${kind} account.`, singular: 'record', endpoint: `/${kind}/${section}`, columns: ['Record', 'Details', 'Status', 'Updated'], empty: 'Records will appear here when they are available.' };
  const [search, setSearch] = useState('');
  const records = useQuery({ queryKey: [kind, section, search], queryFn: () => api.get<PageResult<ActivityRow | Record<string, any>>>(`${config.endpoint}?q=${encodeURIComponent(search)}`) });
  const items = records.data?.items ?? [];

  return <><Seo title={`${config.title} · ${kindLabel[kind]}`} noIndex /><div className="workspace-page"><header className="workspace-page__heading"><div><span className="eyebrow">{kindLabel[kind]}</span><h2>{config.title}</h2><p>{config.intro}</p></div>{config.createPath && <Link className="button button--primary" to={config.createPath}><Plus /> New {config.singular}</Link>}</header><section className="surface-card data-section"><div className="data-toolbar"><label><Search /><span className="sr-only">Search {config.title}</span><input placeholder={`Search ${config.title.toLowerCase()}`} value={search} onChange={(event) => setSearch(event.target.value)} /></label><button className="button button--secondary"><Filter /> Filters</button><button className="button button--secondary"><Download /> Export</button></div>{records.isLoading ? <PageLoader /> : records.isError ? <ErrorState title={`${config.title} unavailable`} message={records.error.message} onRetry={() => void records.refetch()} /> : !items.length ? <EmptyState title={`No ${config.title.toLowerCase()} yet`} message={config.empty} action={config.createPath ? <Link className="button button--primary" to={config.createPath}><Plus /> New {config.singular}</Link> : undefined} /> : <div className="data-table"><table><thead><tr>{config.columns.map((column) => <th key={column}>{column}</th>)}<th><span className="sr-only">Actions</span></th></tr></thead><tbody>{items.map((item, index) => <WorkspaceRow item={item} key={String(item.id ?? index)} section={section} />)}</tbody></table></div>}</section></div></>;
}

function WorkspaceRow({ item, section }: { item: ActivityRow | Record<string, any>; section: string }) {
  const primary = String(item.primary ?? item.name ?? item.orderNumber ?? item.title ?? item.id);
  const secondary = String(item.secondary ?? item.email ?? item.sku ?? item.quantity ?? '—');
  const status = String(item.status ?? 'Active');
  const value = String(item.value ?? item.total ?? item.price ?? '—');
  return <tr><td><strong>{primary}</strong><small>{secondary}</small></td><td>{String(item.quantity ?? item.type ?? item.customer ?? item.role ?? '—')}</td><td><span className={`status status--${status.toLowerCase().replaceAll(' ', '-')}`}>{titleFromSlug(status)}</span></td><td><strong>{value}</strong></td><td><Link className="icon-button icon-button--small" to={`${section}/${item.id}`} aria-label={`View ${primary}`}><ChevronRight /></Link></td></tr>;
}

export function SellerOnboardingPage() {
  const navigate = useNavigate();
  const { notify } = useToast();
  const [step, setStep] = useState(1);
  const [values, setValues] = useState<Record<string, FormDataEntryValue>>({});
  const save = useMutation({ mutationFn: (body: Record<string, FormDataEntryValue>) => api.post('/seller/onboarding/store', { name: body.storeName, description: body.description, supportEmail: body.supportEmail, supportPhone: body.phone, location: body.state }), onSuccess: () => { notify('Your store has been submitted for review.'); navigate('/seller/dashboard'); }, onError: (error) => notify(error.message, 'error') });
  const next = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setValues((current) => ({ ...current, ...Object.fromEntries(new FormData(event.currentTarget)) })); setStep((value) => Math.min(3, value + 1)); };
  const finish = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); save.mutate({ ...values, ...Object.fromEntries(new FormData(event.currentTarget)) }); };
  return <><Seo title="Seller onboarding" noIndex /><div className="workspace-page onboarding-page"><header className="workspace-page__heading"><div><span className="eyebrow">Seller onboarding</span><h2>Set up a store people can trust.</h2><p>You can save progress and return before submitting for review.</p></div></header><ol className="stepper">{['Business', 'Storefront', 'Fulfilment'].map((label, index) => <li className={step >= index + 1 ? 'is-active' : ''} key={label}><span>{step > index + 1 ? <Check /> : index + 1}</span><strong>{label}</strong></li>)}</ol>{step === 1 && <form className="surface-card settings-form" onSubmit={next}><h3>Tell us about the business</h3><div className="form-grid"><label><span>Registered business name</span><input name="legalName" required /></label><label><span>Business type</span><select name="businessType" required><option value="">Choose one</option><option>Individual</option><option>Registered business</option><option>Limited company</option></select></label><label><span>Phone number</span><input name="phone" autoComplete="tel" required /></label><label><span>Operating state</span><input name="state" required /></label></div><button className="button button--primary">Continue <ArrowRight /></button></form>}{step === 2 && <form className="surface-card settings-form" onSubmit={next}><h3>Shape your storefront</h3><label><span>Store name</span><input name="storeName" required /></label><label><span>Store description</span><textarea name="description" rows={4} required /></label><label className="upload-control"><Upload /><span><strong>Store logo</strong><small>Square PNG or JPG recommended</small></span><input type="file" accept="image/png,image/jpeg" /></label><div className="form-actions"><button type="button" className="button button--secondary" onClick={() => setStep(1)}>Back</button><button className="button button--primary">Continue <ArrowRight /></button></div></form>}{step === 3 && <form className="surface-card settings-form" onSubmit={finish}><h3>Fulfilment preferences</h3><label><span>Dispatch address</span><input name="dispatchAddress" required /></label><div className="form-grid"><label><span>Typical handling time</span><select name="handlingTime" required><option value="same-day">Same day</option><option value="one-day">1 business day</option><option value="two-days">2 business days</option></select></label><label><span>Support email</span><input type="email" name="supportEmail" required /></label></div><label className="check-line"><input type="checkbox" required /> I confirm the business information is accurate and agree to marketplace seller standards.</label><div className="form-actions"><button type="button" className="button button--secondary" onClick={() => setStep(2)}>Back</button><button className="button button--primary" disabled={save.isPending}>{save.isPending ? 'Submitting…' : 'Submit for review'}</button></div></form>}</div></>;
}

export function SellerStorePage({ customize = false }: { customize?: boolean }) {
  const { notify } = useToast();
  const store = useQuery({ queryKey: ['seller', 'store'], queryFn: () => api.get<Record<string, any>>('/seller/store') });
  const save = useMutation({ mutationFn: (body: Record<string, FormDataEntryValue>) => api.patch('/seller/store', body), onSuccess: () => notify('Storefront updated.'), onError: (error) => notify(error.message, 'error') });
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); save.mutate(Object.fromEntries(new FormData(event.currentTarget))); };
  return <><Seo title={customize ? 'Customize storefront' : 'Store profile'} noIndex /><div className="workspace-page"><header className="workspace-page__heading"><div><span className="eyebrow">Seller centre</span><h2>{customize ? 'Customize storefront' : 'Store profile'}</h2><p>Keep your public store accurate, distinctive and useful.</p></div>{!customize && <Link className="button button--secondary" to="/seller/store/customize">Customize design</Link>}</header>{store.isLoading ? <PageLoader /> : store.isError ? <ErrorState message={store.error.message} /> : <form className="surface-card settings-form" onSubmit={submit}><div className="store-preview"><span><Store /></span><div><strong>{store.data?.name ?? 'Your store'}</strong><small>{store.data?.slug ? `buysell.ng/store/${store.data.slug}` : 'Public link created after approval'}</small></div><span className="status"><BadgeCheck /> {store.data?.status ?? 'Setup'}</span></div><div className="form-grid"><label><span>Store name</span><input name="name" defaultValue={store.data?.name ?? ''} required /></label><label><span>Support email</span><input name="supportEmail" type="email" defaultValue={store.data?.supportEmail ?? ''} /></label><label className="form-field--full"><span>Store description</span><textarea name="description" rows={5} defaultValue={store.data?.description ?? ''} /></label></div>{customize && <><label><span>Announcement banner</span><input name="announcement" defaultValue={store.data?.announcement ?? ''} placeholder="Free Lagos delivery over ₦100,000" /></label><label className="upload-control"><Upload /><span><strong>Cover image</strong><small>Wide JPG or PNG, up to 5 MB</small></span><input type="file" accept="image/png,image/jpeg" /></label></>}<button className="button button--primary" disabled={save.isPending}>{save.isPending ? 'Saving…' : 'Save storefront'}</button></form>}</div></>;
}

export function ProductEditorPage({ edit = false }: { edit?: boolean }) {
  const { productId = '' } = useParams();
  const navigate = useNavigate();
  const { notify } = useToast();
  const product = useQuery({ queryKey: ['seller', 'product', productId], queryFn: () => api.get<Product>(`/seller/products/${encodeURIComponent(productId)}`), enabled: edit && Boolean(productId) });
  const save = useMutation({ mutationFn: (body: Record<string, unknown>) => edit ? api.patch(`/seller/products/${encodeURIComponent(productId)}`, body) : api.post('/seller/products', body), onSuccess: () => { notify(edit ? 'Product updated.' : 'Product created.'); navigate('/seller/products'); }, onError: (error) => notify(error.message, 'error') });
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const body = Object.fromEntries(new FormData(event.currentTarget)); save.mutate(body); };
  if (product.isLoading) return <PageLoader label="Loading product" />;
  return <><Seo title={edit ? 'Edit product' : 'New product'} noIndex /><div className="workspace-page"><header className="workspace-page__heading"><div><span className="eyebrow">Product catalog</span><h2>{edit ? 'Edit product' : 'Add a product'}</h2><p>Accurate product information builds buyer confidence and reduces returns.</p></div></header><form className="editor-layout" onSubmit={submit}><div className="editor-main"><section className="surface-card settings-form"><h3>Product details</h3><label><span>Product title</span><input name="name" defaultValue={product.data?.name ?? ''} maxLength={120} required /></label><label><span>Description</span><textarea name="description" defaultValue={product.data?.description ?? ''} rows={8} required /></label><div className="form-grid"><label><span>Category</span><select name="categoryId" required><option value="">Select category</option><option value="electronics">Electronics</option><option value="fashion">Fashion</option><option value="home-living">Home & living</option><option value="beauty">Beauty</option></select></label><label><span>Brand</span><input name="brand" /></label></div></section><section className="surface-card settings-form"><h3>Media</h3><label className="upload-control upload-control--large"><Upload /><span><strong>Add product images</strong><small>Use clear JPG, PNG or WebP images. First image becomes the cover.</small></span><input type="file" accept="image/png,image/jpeg,image/webp" multiple /></label></section><section className="surface-card settings-form"><h3>Price & inventory</h3><div className="form-grid"><label><span>Price (NGN)</span><input name="price" inputMode="numeric" defaultValue={product.data?.price ?? ''} required /></label><label><span>Compare-at price</span><input name="compareAtPrice" inputMode="numeric" defaultValue={product.data?.compareAtPrice ?? ''} /></label><label><span>SKU</span><input name="sku" /></label><label><span>Available quantity</span><input name="quantity" type="number" min="0" defaultValue={product.data?.stock ?? 0} required /></label></div></section></div><aside className="editor-side"><section className="surface-card settings-form"><h3>Publishing</h3><label><span>Status</span><select name="status"><option value="DRAFT">Draft</option><option value="ACTIVE">Active</option></select></label><button className="button button--primary button--full" disabled={save.isPending}>{save.isPending ? 'Saving…' : edit ? 'Save changes' : 'Create product'}</button><Link className="button button--text button--full" to="/seller/products">Cancel</Link></section><section className="surface-card helper-card"><ShieldCheck /><h3>Quality checklist</h3><ul><li>Specific, searchable title</li><li>Original, well-lit images</li><li>Honest specifications</li><li>Accurate stock count</li></ul></section></aside></form></div></>;
}

export function SellerSourcingEditorPage() {
  const { requestId } = useParams();
  const { notify } = useToast();
  const navigate = useNavigate();
  const save = useMutation({ mutationFn: (body: Record<string, FormDataEntryValue>) => api.post('/sourcing/requests', { desiredDeliveryAt: body.targetDate || undefined, notes: body.description, items: [{ title: body.productName, description: body.description, quantity: Number(body.quantity), referenceUrl: body.referenceUrl || undefined }] }), onSuccess: () => { notify('Sourcing request submitted.'); navigate('/seller/sourcing'); }, onError: (error) => notify(error.message, 'error') });
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); save.mutate(Object.fromEntries(new FormData(event.currentTarget))); };
  return <><Seo title={requestId ? 'Sourcing request' : 'New sourcing request'} noIndex /><div className="workspace-page"><header className="workspace-page__heading"><div><span className="eyebrow">Product sourcing</span><h2>{requestId ? `Request ${requestId}` : 'Request a quote'}</h2><p>Share any reference and the details your business needs.</p></div></header><form className="surface-card settings-form narrow-form" onSubmit={submit}><label><span>Product name</span><input name="productName" required /></label><label><span>Reference URL <small>optional</small></span><input name="referenceUrl" type="url" placeholder="https://example.com/item" /></label><div className="form-grid"><label><span>Quantity</span><input name="quantity" type="number" min="1" required /></label><label><span>Target date</span><input name="targetDate" type="date" /></label></div><label><span>Specifications</span><textarea name="description" rows={6} required /></label><p className="form-note">Reference files can be added securely after the request is created.</p><button className="button button--primary" disabled={save.isPending}>{save.isPending ? 'Saving…' : 'Submit for review'}</button></form></div></>;
}

export function WorkspaceDetailPage({ kind, section }: { kind: WorkspaceKind; section: string }) {
  const params = useParams();
  const id = Object.values(params)[0] ?? '';
  const endpoint = `/${kind}/${section}/${encodeURIComponent(id)}`;
  const record = useQuery({ queryKey: [kind, section, id], queryFn: () => api.get<Record<string, any>>(endpoint) });
  const { notify } = useToast();
  const action = useMutation({ mutationFn: (input: { action: string }) => api.post(`${endpoint}/actions`, input), onSuccess: () => { notify('Action completed.'); void record.refetch(); }, onError: (error) => notify(error.message, 'error') });
  return <><Seo title={`${titleFromSlug(section)} record`} noIndex /><div className="workspace-page"><Link className="back-link" to={`/${kind}/${section}`}>← Back to {titleFromSlug(section)}</Link>{record.isLoading ? <PageLoader /> : record.isError ? <ErrorState title="Record unavailable" message={record.error.message} onRetry={() => void record.refetch()} /> : <><header className="workspace-page__heading"><div><span className="eyebrow">{titleFromSlug(section)}</span><h2>{record.data?.name ?? record.data?.title ?? record.data?.orderNumber ?? id}</h2><p>{record.data?.description ?? 'Review the full record and its audit trail.'}</p></div><span className="status">{titleFromSlug(record.data?.status ?? 'Active')}</span></header><div className="record-grid"><section className="surface-card record-details"><h3>Details</h3><dl>{Object.entries(record.data ?? {}).filter(([key, value]) => !['id', 'description'].includes(key) && ['string', 'number', 'boolean'].includes(typeof value)).slice(0, 12).map(([key, value]) => <div key={key}><dt>{titleFromSlug(key)}</dt><dd>{key.toLowerCase().includes('price') || key.toLowerCase().includes('total') ? formatMoney(value as number) : String(value)}</dd></div>)}</dl></section><aside className="surface-card settings-form"><h3>Actions</h3><p>Available actions depend on the record state and your permissions.</p><button className="button button--primary button--full" onClick={() => action.mutate({ action: 'advance' })}>Advance status</button><button className="button button--secondary button--full" onClick={() => action.mutate({ action: 'note' })}>Add internal note</button></aside></div></>}</div></>;
}

interface AdminConfig {
  title: string;
  intro: string;
  endpoint: string;
  columns: string[];
  empty: string;
  createPath?: string;
}

const adminConfig: Record<string, AdminConfig> = {
  users: { title: 'Users', intro: 'Review accounts, access and marketplace participation.', endpoint: '/admin/users', columns: ['User', 'Roles', 'Status', 'Joined'], empty: 'No users match this view.' },
  buyers: { title: 'Buyers', intro: 'Understand buyer activity without exposing unnecessary personal data.', endpoint: '/admin/buyers', columns: ['Buyer', 'Orders', 'Status', 'Value'], empty: 'No buyers match this view.' },
  sellers: { title: 'Sellers', intro: 'Review seller status, store health and verification.', endpoint: '/admin/sellers', columns: ['Seller', 'Store', 'Status', 'Sales'], empty: 'No sellers match this view.' },
  suppliers: { title: 'Suppliers', intro: 'Manage distinct supplier profiles, capabilities and verification.', endpoint: '/admin/suppliers', columns: ['Supplier', 'Capability', 'Status', 'Updated'], empty: 'No suppliers match this view.' },
  products: { title: 'Product moderation', intro: 'Review marketplace listings and quality signals.', endpoint: '/admin/products', columns: ['Product', 'Seller', 'Status', 'Price'], empty: 'No products require review.' },
  categories: { title: 'Categories', intro: 'Maintain a useful, stable marketplace taxonomy.', endpoint: '/admin/categories', columns: ['Category', 'Products', 'Status', 'Updated'], empty: 'No categories are available.' },
  orders: { title: 'Orders', intro: 'Inspect order state, fulfilment and support context.', endpoint: '/admin/orders', columns: ['Order', 'Buyer', 'Status', 'Total'], empty: 'No orders match this view.' },
  payments: { title: 'Payments', intro: 'Monitor provider verification, reconciliation and exceptions.', endpoint: '/admin/payments', columns: ['Payment', 'Order', 'Status', 'Amount'], empty: 'No payment records match this view.' },
  finance: { title: 'Marketplace finance', intro: 'Review the immutable ledger, balances and reconciliation.', endpoint: '/admin/finance', columns: ['Entry', 'Account', 'Type', 'Amount'], empty: 'No finance entries match this view.' },
  commissions: { title: 'Commissions', intro: 'Review platform commission entries and calculation rules.', endpoint: '/admin/commissions', columns: ['Order', 'Seller', 'Rate', 'Commission'], empty: 'No commission entries match this view.' },
  payouts: { title: 'Payout operations', intro: 'Review holds, approvals, provider status and release history.', endpoint: '/admin/payouts', columns: ['Payout', 'Seller', 'Status', 'Amount'], empty: 'No payouts match this view.' },
  disputes: { title: 'Disputes', intro: 'Resolve buyer and seller cases with complete order evidence.', endpoint: '/admin/disputes', columns: ['Case', 'Order', 'Priority', 'Status'], empty: 'No disputes match this view.' },
  kyc: { title: 'Verification queue', intro: 'Review sensitive identity and business documents with least-privilege access.', endpoint: '/admin/kyc', columns: ['Submission', 'Owner', 'Type', 'Status'], empty: 'No verification submissions need review.' },
  sourcing: { title: 'Sourcing operations', intro: 'Review public requests alongside restricted procurement details.', endpoint: '/admin/sourcing', columns: ['Request', 'Requester', 'Status', 'Quote'], empty: 'No sourcing requests match this view.' },
  advertising: { title: 'Advertising', intro: 'Moderate campaigns, placements and campaign spend.', endpoint: '/admin/advertising', columns: ['Campaign', 'Seller', 'Status', 'Spend'], empty: 'No advertising campaigns match this view.' },
  broadcasts: { title: 'Broadcasts', intro: 'Create targeted, auditable marketplace communications.', endpoint: '/admin/broadcasts', columns: ['Campaign', 'Audience', 'Status', 'Delivery'], empty: 'No broadcasts have been created.', createPath: '/admin/broadcasts/new' },
  messages: { title: 'Message oversight', intro: 'Review escalated communications with a documented reason.', endpoint: '/admin/messages', columns: ['Conversation', 'Participants', 'Status', 'Updated'], empty: 'No conversations are escalated.' },
  notifications: { title: 'Notifications', intro: 'Review notification templates, delivery and failures.', endpoint: '/admin/notifications', columns: ['Notification', 'Channel', 'Status', 'Delivered'], empty: 'No notification activity matches this view.' },
  analytics: { title: 'Marketplace analytics', intro: 'Analyse trustworthy server-side marketplace data.', endpoint: '/admin/analytics', columns: ['Report', 'Period', 'Status', 'Updated'], empty: 'No reports are available.' },
  'audit-logs': { title: 'Audit logs', intro: 'Trace privileged actions across the platform.', endpoint: '/admin/audit-logs', columns: ['Actor', 'Action', 'Target', 'Occurred'], empty: 'No audit events match this view.' },
  settings: { title: 'Platform settings', intro: 'Manage validated operational settings with an audit trail.', endpoint: '/admin/settings', columns: ['Setting', 'Scope', 'Status', 'Updated'], empty: 'No platform settings are available.' },
  content: { title: 'Content', intro: 'Manage approved marketplace guidance and editorial content.', endpoint: '/admin/content', columns: ['Content', 'Type', 'Status', 'Updated'], empty: 'No content records match this view.' },
};

export function AdminListPage({ section }: { section: string }) {
  const config = adminConfig[section] ?? { title: titleFromSlug(section), intro: `Manage ${titleFromSlug(section).toLowerCase()} across BUYSELL.`, endpoint: `/admin/${section}`, columns: ['Record', 'Owner', 'Status', 'Updated'], empty: 'No records match this view.' };
  const [query, setQuery] = useState('');
  const records = useQuery({ queryKey: ['admin', section, query], queryFn: () => api.get<PageResult<ActivityRow | Record<string, any>>>(`${config.endpoint}?q=${encodeURIComponent(query)}`) });
  return <><Seo title={`${config.title} · Control room`} noIndex /><div className="workspace-page"><header className="workspace-page__heading"><div><span className="eyebrow">Control room</span><h2>{config.title}</h2><p>{config.intro}</p></div>{config.createPath && <Link className="button button--primary" to={config.createPath}><Plus /> New broadcast</Link>}</header><section className="surface-card data-section"><div className="data-toolbar"><label><Search /><span className="sr-only">Search {config.title}</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder={`Search ${config.title.toLowerCase()}`} /></label><button className="button button--secondary"><Filter /> Filters</button><button className="button button--secondary"><Download /> Export</button></div>{records.isLoading ? <PageLoader /> : records.isError ? <ErrorState title={`${config.title} unavailable`} message={records.error.message} onRetry={() => void records.refetch()} /> : !records.data?.items.length ? <EmptyState title={`No ${config.title.toLowerCase()}`} message={config.empty} /> : <div className="data-table"><table><thead><tr>{config.columns.map((column) => <th key={column}>{column}</th>)}<th><span className="sr-only">Actions</span></th></tr></thead><tbody>{records.data.items.map((item, index) => <WorkspaceRow item={item} section={section} key={String(item.id ?? index)} />)}</tbody></table></div>}</section></div></>;
}

export function AdminBroadcastEditorPage() {
  const { campaignId } = useParams();
  const { notify } = useToast();
  const navigate = useNavigate();
  const save = useMutation({ mutationFn: (body: Record<string, FormDataEntryValue>) => campaignId ? api.patch(`/admin/broadcasts/${encodeURIComponent(campaignId)}`, body) : api.post('/admin/broadcasts', body), onSuccess: () => { notify('Broadcast saved.'); navigate('/admin/broadcasts'); }, onError: (error) => notify(error.message, 'error') });
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); save.mutate(Object.fromEntries(new FormData(event.currentTarget))); };
  return <><Seo title={campaignId ? 'Edit broadcast' : 'New broadcast'} noIndex /><div className="workspace-page"><header className="workspace-page__heading"><div><span className="eyebrow">Controlled communication</span><h2>{campaignId ? 'Edit broadcast' : 'Create broadcast'}</h2><p>Choose a clear audience and preview the content before scheduling.</p></div></header><form className="editor-layout" onSubmit={submit}><div className="editor-main"><section className="surface-card settings-form"><h3>Message</h3><label><span>Campaign name</span><input name="name" required /></label><label><span>Title</span><input name="title" maxLength={80} required /></label><label><span>Body</span><textarea name="body" rows={7} maxLength={600} required /></label></section><section className="surface-card settings-form"><h3>Audience</h3><label><span>Segment</span><select name="audience" required><option value="">Choose audience</option><option value="all-buyers">All active buyers</option><option value="all-sellers">All active sellers</option><option value="seller-action">Sellers requiring action</option></select></label><label><span>Channel</span><select name="channel"><option value="in-app">In-app notification</option><option value="email">Email</option><option value="push">Push notification</option></select></label></section></div><aside className="editor-side"><section className="surface-card settings-form"><h3>Schedule</h3><label><span>Send at</span><input type="datetime-local" name="scheduledAt" /></label><button className="button button--primary button--full" disabled={save.isPending}>{save.isPending ? 'Saving…' : 'Save broadcast'}</button><Link className="button button--text button--full" to="/admin/broadcasts">Cancel</Link></section><section className="surface-card helper-card"><ShieldCheck /><h3>Before sending</h3><ul><li>Audience is necessary and proportionate</li><li>Copy is accurate and action-oriented</li><li>Links use approved BUYSELL routes</li></ul></section></aside></form></div></>;
}

export function FinancePage({ admin = false }: { admin?: boolean }) {
  const endpoint = admin ? '/admin/finance' : '/seller/finance';
  const finance = useQuery({ queryKey: [admin ? 'admin' : 'seller', 'finance-summary'], queryFn: () => api.get<DashboardData>(endpoint) });
  return <><Seo title={admin ? 'Marketplace finance' : 'Store finance'} noIndex /><div className="workspace-page"><header className="workspace-page__heading"><div><span className="eyebrow">{admin ? 'Control room' : 'Seller centre'}</span><h2>{admin ? 'Marketplace finance' : 'Finance'}</h2><p>{admin ? 'Reconcile platform money movement against provider-confirmed events.' : 'See settled sales, deductions and funds available for payout.'}</p></div><button className="button button--secondary"><Download /> Download statement</button></header>{finance.isLoading ? <PageLoader /> : finance.isError ? <ErrorState message={finance.error.message} onRetry={() => void finance.refetch()} /> : finance.data && <><MetricGrid metrics={finance.data.metrics} /><RecentActivity title="Recent transactions" rows={finance.data.rows} /></>}</div></>;
}
