import { Router } from 'express';
import { query } from '../../db/pool.js';
import { requireAuth, requireRole } from '../../middleware/auth.js';
import { asyncHandler, HttpError } from '../../utils/http.js';
export const deliveriesRouter=Router();
deliveriesRouter.get('/dashboard',requireAuth,requireRole('rider','admin'),asyncHandler(async(req,res)=>{const admin=req.user.roles.includes('admin');const args=admin?[]:[req.user.id];const where=admin?'TRUE':'rider_id=$1';const {rows}=await query(`SELECT count(*)::int total,count(*) FILTER(WHERE status IN ('assigned','picked_up','in_transit'))::int active,count(*) FILTER(WHERE status='delivered')::int delivered,COALESCE(sum(fee) FILTER(WHERE status='delivered'),0)::bigint earnings FROM deliveries WHERE ${where}`,args);res.json(rows[0]);}));
deliveriesRouter.get('/earnings',requireAuth,requireRole('rider','admin'),asyncHandler(async(req,res)=>{const admin=req.user.roles.includes('admin');const args=admin?[]:[req.user.id];const where=admin?"status='delivered'":"rider_id=$1 AND status='delivered'";const {rows}=await query(`SELECT count(*)::int deliveries,COALESCE(sum(fee),0)::bigint earnings FROM deliveries WHERE ${where}`,args);res.json(rows[0]);}));
deliveriesRouter.get('/',requireAuth,requireRole('rider','admin'),asyncHandler(async(req,res)=>{const admin=req.user.roles.includes('admin');const {rows}=await query(admin?'SELECT * FROM deliveries ORDER BY created_at DESC':'SELECT * FROM deliveries WHERE rider_id=$1 ORDER BY created_at DESC',admin?[]:[req.user.id]);res.json(rows);}));
deliveriesRouter.patch('/:id',requireAuth,requireRole('rider','admin'),asyncHandler(async(req,res)=>{const allowed=['assigned','picked_up','in_transit','delivered','failed'];if(!allowed.includes(req.body.status))throw new HttpError(400,'Invalid delivery status');const {rows}=await query(`UPDATE deliveries SET status=$1,notes=COALESCE($2,notes),delivered_at=CASE WHEN $1='delivered' THEN now() ELSE delivered_at END WHERE id=$3 AND (rider_id=$4 OR $5::boolean) RETURNING *`,[req.body.status,req.body.notes||null,req.params.id,req.user.id,req.user.roles.includes('admin')]);if(!rows[0])throw new HttpError(404,'Delivery not found');if(req.body.status==='delivered')await query(`UPDATE orders SET status='delivered' WHERE id=$1`,[rows[0].order_id]);res.json(rows[0]);}));
