import{useEffect,useState}from'react';import{api}from'../../api/client.js';
const configs={
 users:{title:'Users',endpoint:'/admin/users',label:r=>r.name||r.email,actions:[['active','Activate'],['suspended','Suspend']]},
 sellers:{title:'Sellers',endpoint:'/admin/sellers',label:r=>r.store_name||r.name||r.email,actions:[['active','Activate'],['suspended','Suspend']]},
 orders:{title:'Orders',endpoint:'/admin/orders',label:r=>r.order_number||r.id,actions:[['confirmed','Confirm'],['processing','Processing'],['shipped','Shipped'],['cancelled','Cancel']]},
 disputes:{title:'Disputes',endpoint:'/admin/disputes',label:r=>`${r.dispute_type||'Dispute'} · ${r.order_id?.slice(0,8)||''}`,actions:[['resolved','Resolve'],['refunded','Refund'],['rejected','Reject']]},
 withdrawals:{title:'Withdrawals',endpoint:'/admin/withdrawals',label:r=>r.name||r.store_name||r.seller_id,actions:[['paid','Mark paid'],['rejected','Reject']]},
 kyc:{title:'KYC',endpoint:'/admin/kyc',label:r=>r.name||r.full_name||r.user_id,actions:[['approved','Approve'],['rejected','Reject']]},
 ads:{title:'Advertisements',endpoint:'/admin/ads',label:r=>r.title||r.id,actions:[['active','Approve'],['rejected','Reject'],['expired','Expire']]},
 receipts:{title:'Commission receipts',endpoint:'/admin/receipts',label:r=>r.transaction_ref||r.seller_id,actions:[['approved','Approve'],['rejected','Reject']]},
};
const money=v=>`₦${(Number(v||0)/100).toLocaleString('en-NG',{maximumFractionDigits:2})}`;
export function AdminOperationsPage({type}){const cfg=configs[type],[rows,setRows]=useState([]),[error,setError]=useState('');async function load(){try{setRows(await api(cfg.endpoint))}catch(e){setError(e.message)}}useEffect(()=>{load()},[type]);async function act(row,status){try{let path,body={status};if(type==='users'||type==='sellers')path=`/admin/users/${row.id}/status`;else path=`/admin/${type}/${row.id}`;if(['disputes','withdrawals','kyc','receipts'].includes(type)&&['rejected','refunded'].includes(status)){const reason=prompt('Optional note/reason')||'';body.reason=reason;body.resolution_note=reason}await api(path,{method:'PATCH',body:JSON.stringify(body)});load()}catch(e){setError(e.message)}}return <div><h1>{cfg.title}</h1><p className="muted">Server-authorized moderation actions replace direct browser writes to the old database.</p>{error&&<p className="error">{error}</p>}<div className="resource-table">{rows.map((r,i)=><div className="resource-row" key={r.id||i}><div><strong>{cfg.label(r)}</strong>{r.amount!=null&&<small className="muted"> · {money(r.amount)}</small>}{r.total_amount!=null&&<small className="muted"> · {money(r.total_amount)}</small>}</div><span>{r.status||r.kyc_status||(r.roles||[]).join(', ')}</span><div className="card-actions">{cfg.actions.map(([status,label])=><button key={status} className="button small secondary" onClick={()=>act(r,status)}>{label}</button>)}</div></div>)}{!rows.length&&<div className="empty-panel">No records.</div>}</div></div>}
