import { useEffect,useState } from 'react';
import { useLocation } from 'react-router-dom';
import { api,tokenStore } from '../../api/client.js';

export function AccountPage(){
  const location=useLocation(),addressesMode=location.pathname.endsWith('/addresses');
  const [profile,setProfile]=useState(null),[addresses,setAddresses]=useState([]),[error,setError]=useState(''),[saved,setSaved]=useState('');
  const load=()=>Promise.all([api('/profile/me'),api('/profile/me/addresses')]).then(([p,a])=>{setProfile(p);setAddresses(a)}).catch(e=>setError(e.message));
  useEffect(()=>{load()},[]);
  if(!profile&&!error)return <div className="page-wrap">Loading account…</div>;
  const saveProfile=async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.currentTarget));const p=await api('/profile/me',{method:'PATCH',body:JSON.stringify(data)});setProfile(x=>({...x,...p}));setSaved('Profile saved.')};
  const addAddress=async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.currentTarget));data.is_default=Boolean(data.is_default);const a=await api('/profile/me/addresses',{method:'POST',body:JSON.stringify(data)});setAddresses(x=>[a,...x]);e.currentTarget.reset()};
  const remove=async id=>{await api(`/profile/me/addresses/${id}`,{method:'DELETE'});setAddresses(x=>x.filter(a=>a.id!==id))};
  const deleteAccount=async()=>{if(!confirm('Permanently delete your BUYSELL account?'))return;await api('/profile/me',{method:'DELETE'});tokenStore.clear();window.location.assign('/auth')};
  return <div className="page-wrap narrow"><h1>{addressesMode?'Delivery addresses':'Your account'}</h1><p className="muted">Manage identity, seller details, payout profile and delivery addresses without modal dialogs.</p>{error&&<p className="error">{error}</p>}{!addressesMode&&profile&&<form className="form-card stack" onSubmit={saveProfile}><label>Name<input name="name" defaultValue={profile.name||''}/></label><label>Phone<input name="phone" defaultValue={profile.phone||''}/></label><label>WhatsApp<input name="whatsapp" defaultValue={profile.whatsapp||''}/></label><label>Store name<input name="store_name" defaultValue={profile.store_name||''}/></label><label>Store description<textarea name="store_description" defaultValue={profile.store_description||''}/></label><label>Store address<input name="store_address" defaultValue={profile.store_address||''}/></label><label>Bank name<input name="bank_name" defaultValue={profile.bank_name||''}/></label><label>Account number<input name="account_number" defaultValue={profile.account_number||''}/></label><label>Account name<input name="account_name" defaultValue={profile.account_name||''}/></label>{saved&&<p className="success">{saved}</p>}<button className="button">Save profile</button><button type="button" className="button secondary danger-text" onClick={deleteAccount}>Delete my account</button></form>}<section className="section-gap"><h2>Addresses</h2><div className="list">{addresses.map(a=><div className="list-row" key={a.id}><div><strong>{a.label||a.recipient_name}</strong><p>{a.line1}{a.city?`, ${a.city}`:''}{a.state?`, ${a.state}`:''}</p></div><button className="text-btn danger-text" onClick={()=>remove(a.id)}>Remove</button></div>)}</div><form className="form-card stack section-gap" onSubmit={addAddress}><h3>Add address</h3><input name="label" placeholder="Home, Office…"/><input name="recipient_name" placeholder="Recipient name" required/><input name="phone" placeholder="Phone"/><input name="line1" placeholder="Street address" required/><input name="city" placeholder="City"/><input name="state" placeholder="State"/><label className="check"><input type="checkbox" name="is_default"/> Make default</label><button className="button secondary">Add address</button></form></section></div>
}
