import { useEffect,useState } from 'react';
import { api,uploadFile } from '../../api/client.js';

export function KycPage(){
 const [current,setCurrent]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const load=()=>api('/kyc/me').then(setCurrent).catch(e=>setError(e.message));useEffect(()=>{load()},[]);
 const submit=async e=>{e.preventDefault();setBusy(true);setError('');try{const fd=new FormData(e.currentTarget);const payload={document_type:fd.get('document_type'),document_number:fd.get('document_number'),full_name:fd.get('full_name')};for(const key of ['front','back','selfie']){const f=fd.get(key);if(f?.size){const up=await uploadFile(f);payload[`${key}_url`]=up.url;}}const row=await api('/kyc',{method:'POST',body:JSON.stringify(payload)});setCurrent(row);e.currentTarget.reset()}catch(e){setError(e.message)}finally{setBusy(false)}};
 return <div className="page-wrap narrow"><h1>Identity verification</h1><p className="muted">KYC is a dedicated account page. Documents are uploaded through the BUYSELL backend and never directly from the browser to the database.</p>{current&&<div className="notice section-gap"><strong>Status: {current.status}</strong><p>{current.admin_note||'Your latest verification submission is on record.'}</p></div>}{error&&<p className="error">{error}</p>}<form className="form-card stack section-gap" onSubmit={submit}><select name="document_type" required><option value="">Document type</option><option value="nin">NIN</option><option value="drivers_license">Driver’s licence</option><option value="passport">International passport</option><option value="voters_card">Voter’s card</option></select><input name="document_number" placeholder="Document number" required/><input name="full_name" placeholder="Full legal name" required/><label>Document front<input name="front" type="file" accept="image/*,application/pdf" required/></label><label>Document back<input name="back" type="file" accept="image/*,application/pdf"/></label><label>Selfie<input name="selfie" type="file" accept="image/*" required/></label><button className="button" disabled={busy}>{busy?'Uploading…':'Submit verification'}</button></form></div>
}
