import{useEffect,useState}from'react';
import{useNavigate,useParams}from'react-router-dom';
import{api,uploadFile}from'../../api/client.js';
import{useAuth}from'../../auth/AuthContext.jsx';

const empty={name:'',description:'',price:'',original_price:'',shipping_fee:'',category:'',condition:'new',location:'',stock_quantity:0,status:'draft',negotiable:false,image_url:'',video_url:''};
export function ProductFormPage(){
 const{id}=useParams(),nav=useNavigate(),{user}=useAuth(),[form,setForm]=useState(empty),[assignments,setAssignments]=useState([]),[sellerId,setSellerId]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{if(id)api(`/products/${id}`).then(p=>setForm({...empty,...p,price:Number(p.price||0)/100,original_price:p.original_price?Number(p.original_price)/100:'',shipping_fee:Number(p.shipping_fee||0)/100})).catch(e=>setError(e.message))},[id]);
 useEffect(()=>{if(user?.roles?.includes('seller_manager'))api('/sellers/assignments').then(rows=>{setAssignments(rows);if(rows[0])setSellerId(rows[0].seller_id)}).catch(e=>setError(e.message))},[user]);
 const change=(key,value)=>setForm(x=>({...x,[key]:value}));
 async function submit(e){e.preventDefault();setBusy(true);setError('');try{const fd=new FormData(e.currentTarget);let image=form.image_url||null,video=form.video_url||null;const imageFile=fd.get('image_file'),videoFile=fd.get('video_file');if(imageFile?.size)image=(await uploadFile(imageFile)).url;if(videoFile?.size)video=(await uploadFile(videoFile)).url;const payload={...form,name:form.name.trim(),price:Math.round(Number(form.price)*100),original_price:form.original_price===''?null:Math.round(Number(form.original_price)*100),shipping_fee:Math.round(Number(form.shipping_fee||0)*100),stock_quantity:Number(form.stock_quantity||0),image_url:image,images:image?[image]:[],video_url:video,videos:video?[video]:[],seller_id:sellerId||undefined};if(id)await api(`/products/${id}`,{method:'PATCH',body:JSON.stringify(payload)});else await api('/products',{method:'POST',body:JSON.stringify(payload)});nav(user?.roles?.includes('seller_manager')?'/manager/products':'/seller/products')}catch(e){setError(e.message)}finally{setBusy(false)}}
 return <div><h1>{id?'Edit product':'Add product'}</h1><p className="muted">Product media uploads through the backend storage layer. Prices are entered in NGN and stored as integer kobo.</p><form className="stack form-card" onSubmit={submit}>{user?.roles?.includes('seller_manager')&&<label>Managed store<select value={sellerId} onChange={e=>setSellerId(e.target.value)} required>{assignments.map(a=><option value={a.seller_id} key={a.seller_id}>{a.store_name||a.name||a.email}</option>)}</select></label>}<input required placeholder="Product name" value={form.name} onChange={e=>change('name',e.target.value)}/><textarea placeholder="Description" value={form.description||''} onChange={e=>change('description',e.target.value)}/><div className="form-grid"><input required type="number" min="0" step="0.01" placeholder="Price (NGN)" value={form.price} onChange={e=>change('price',e.target.value)}/><input type="number" min="0" step="0.01" placeholder="Original price (NGN)" value={form.original_price||''} onChange={e=>change('original_price',e.target.value)}/><input type="number" min="0" step="0.01" placeholder="Shipping fee (NGN)" value={form.shipping_fee||''} onChange={e=>change('shipping_fee',e.target.value)}/><input type="number" min="0" placeholder="Stock" value={form.stock_quantity} onChange={e=>change('stock_quantity',e.target.value)}/></div><input placeholder="Category" value={form.category||''} onChange={e=>change('category',e.target.value)}/><div className="form-grid"><select value={form.condition||'new'} onChange={e=>change('condition',e.target.value)}><option value="new">New</option><option value="used">Used</option><option value="refurbished">Refurbished</option></select><input placeholder="Location" value={form.location||''} onChange={e=>change('location',e.target.value)}/></div><label>Product image<input name="image_file" type="file" accept="image/*"/></label>{form.image_url&&<img className="form-preview" src={form.image_url} alt="Current product"/>}<label>Optional product video<input name="video_file" type="file" accept="video/*"/></label><label className="check"><input type="checkbox" checked={Boolean(form.negotiable)} onChange={e=>change('negotiable',e.target.checked)}/> Price negotiable</label><select value={form.status} onChange={e=>change('status',e.target.value)}><option value="draft">Draft</option><option value="active">Active</option><option value="paused">Paused</option><option value="archived">Archived</option></select>{error&&<p className="error">{error}</p>}<button disabled={busy} className="button">{busy?'Saving…':'Save product'}</button></form></div>
}
