import { Router } from 'express';
import { healthRouter } from './modules/health/routes.js';
import { authRouter } from './modules/auth/routes.js';
import { productsRouter } from './modules/products/routes.js';
import { profilesRouter } from './modules/profiles/routes.js';
import { reviewsRouter } from './modules/reviews/routes.js';
import { ordersRouter } from './modules/orders/routes.js';
import { messagesRouter } from './modules/messages/routes.js';
import { paymentsRouter } from './modules/payments/routes.js';
import { withdrawalsRouter } from './modules/withdrawals/routes.js';
import { disputesRouter } from './modules/disputes/routes.js';
import { sellersRouter } from './modules/sellers/routes.js';
import { dropshipRouter } from './modules/dropship/routes.js';
import { kycRouter } from './modules/kyc/routes.js';
import { couponsRouter } from './modules/coupons/routes.js';
import { adsRouter } from './modules/ads/routes.js';
import { notificationsRouter } from './modules/notifications/routes.js';
import { analyticsRouter } from './modules/analytics/routes.js';
import { uploadsRouter } from './modules/uploads/routes.js';
import { deliveriesRouter } from './modules/deliveries/routes.js';
import { adminRouter } from './modules/admin/routes.js';
import { aiRouter } from './modules/ai/routes.js';
import { collectionsRouter } from './modules/collections/routes.js';
import { upcomingRouter } from './modules/upcoming/routes.js';
import { referralsRouter } from './modules/referrals/routes.js';
import { broadcastsRouter } from './modules/broadcasts/routes.js';
import { suppliersRouter } from './modules/suppliers/routes.js';

export const apiRouter=Router();
apiRouter.use('/health',healthRouter);
apiRouter.use('/auth',authRouter);
apiRouter.use('/products',productsRouter);
apiRouter.use('/collections',collectionsRouter);
apiRouter.use('/upcoming',upcomingRouter);
apiRouter.use('/referrals',referralsRouter);
apiRouter.use('/broadcasts',broadcastsRouter);
apiRouter.use('/suppliers',suppliersRouter);
apiRouter.use('/profile',profilesRouter);
apiRouter.use('/reviews',reviewsRouter);
apiRouter.use('/orders',ordersRouter);
apiRouter.use('/messages',messagesRouter);
apiRouter.use('/payments',paymentsRouter);
apiRouter.use('/withdrawals',withdrawalsRouter);
apiRouter.use('/disputes',disputesRouter);
apiRouter.use('/sellers',sellersRouter);
apiRouter.use('/dropship',dropshipRouter);
apiRouter.use('/kyc',kycRouter);
apiRouter.use('/coupons',couponsRouter);
apiRouter.use('/ads',adsRouter);
apiRouter.use('/notifications',notificationsRouter);
apiRouter.use('/analytics',analyticsRouter);
apiRouter.use('/uploads',uploadsRouter);
apiRouter.use('/deliveries',deliveriesRouter);
apiRouter.use('/admin',adminRouter);
apiRouter.use('/ai',aiRouter);
